# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef68e5d8514b8808162e28be38540d79b801296253f6d1e4871c810bf7aaf93ebf34c5dd0f09828ecb059b4082ccb83939a15dddde7553576b2de441936be7a6

test:
  secret_key_base: 329d6724222bbf60aafecfd034bf58fa3077730fb6e1bf7b7afd8cfedc63b56cdb228d7c6889afd78c41c83eeaa33518740127add9da21fc1b00c32a65ed21f7

staging:
  secret_key_base: 5f3d4fa6b79662e7618a3034199242a63192a81628c9bbc14ea56a2122275e6f50bbdb0e8fc9d5a916e537d37da55839aa040ba75d0d39a62aa05dc713a81120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
